### ISSUE TITLE
among us theme

### ISSUE THREAD

**Issue by Synth0** [a456pur/seraph#47] opened 2023-11-19 22:36 UTC
there is still no among us theme. This is making me among sad.
![image](https://github.com/a456pur/seraph/assets/94086709/dee65c69-daec-4351-9d3d-dc013680e61e)
![image](https://github.com/a456pur/seraph/assets/94086709/43315ada-ab37-4571-9bed-e461fca8c0dc)
![image](https://github.com/a456pur/seraph/assets/94086709/f3386d33-4473-437a-b5b9-76c50280cf51)
![image](https://github.com/a456pur/seraph/assets/94086709/48b46077-f904-4ab4-aa03-a35ef7c256ca)
![image](https://github.com/a456pur/seraph/assets/94086709/7424256f-03b0-4c5b-af1a-34dbb9aeb7c2)
![image](https://github.com/a456pur/seraph/assets/94086709/69986b91-2915-4100-a056-68791657161b)
![image](https://github.com/a456pur/seraph/assets/94086709/af6a46f0-191c-44ee-8722-2cfdc7e79dca)
![image](https://github.com/a456pur/seraph/assets/94086709/77fb0165-e2c5-434c-8c1f-16cd5a3fd922)
![image](https://github.com/a456pur/seraph/assets/94086709/cfc4c015-eaac-4a4f-b861-87d41825a9d1)
![image](https://github.com/a456pur/seraph/assets/94086709/86cc52ac-23a0-4a54-a877-af52b20bc2d3)
![image](https://github.com/a456pur/seraph/assets/94086709/1127c3c6-8296-4cbc-8d3b-fd14e9dba4d4)
![image](https://github.com/a456pur/seraph/assets/94086709/d83df4f4-a65c-4224-864c-bd12be1a0178)
![image](https://github.com/a456pur/seraph/assets/94086709/06ff9451-46a0-4ce7-8bb0-bd87215a0ee5)
![image](https://github.com/a456pur/seraph/assets/94086709/c8215dd3-aae7-4837-bbb4-671193f8f9e5)
![image](https://github.com/a456pur/seraph/assets/94086709/c6fbce26-599a-4133-9de7-8adf91a61b7b)
![image](https://github.com/a456pur/seraph/assets/94086709/ac0a1fe7-08cb-4b0a-a82d-818338baed09)
![image](https://github.com/a456pur/seraph/assets/94086709/0121c441-ea65-4385-adea-59dcc68dfd46)

**Comment by a456pur** [comment] 2023-11-20 03:34
duplicate of #36

**Closed by a456pur** 2023-11-20 03:34 UTC
